# meilisync configuration

debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: postgres
  host: postgres
  port: 5432
  user: postgres
  password: abcd1abcd1abcdabcdabcdabcdabcdabcdabcdabcdabcd
  database: v_1
meilisearch:
  api_url: http://meilisearch:7700
  api_key: abcd1abcd1abcdabcdabcdabcdabcdabcdabcdabcdabcd
  insert_size: 1000
  insert_interval: 10
sync:
  - table: speeds_speed
    index: speeds
    plugins:
      - meilisync.plugin.Plugin
sentry:
  dsn: ""
  environment: "production"